services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      # Always use the docker-compose service name for the db when starting the app with docker compose.
      - PGHOST=db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - app-network
  db:
    image: postgres:17
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./dev-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER} -d ${PGDATABASE}"]
      interval: 1s
      retries: 5
    networks:
      - app-network
networks:
  app-network:
